export const EmptyAmpFormData = {
	brand: "",
	model: "",
	submodel: "",
	year: "",
	country: "",
	condition: "",
	serial: "",
	power: "",
	formFactor: "",
	type: "",
	voltage: "",
	color: "",
	grillCloth: "",
	panel: "",
	preampTubes: "",
	powerTubes: "",
	rectifier: "",
	phaseInverter: "",
	controls: "",
	channels: "",
	inputs: "",
	speakers: "",
	effectsLoop: false,
	onboardEffects: "",
	outputs: "",
	outputImpedance: "",
};

export type AmpFormData = typeof EmptyAmpFormData;
